# Generated by Django 3.0.4 on 2020-04-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200410_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(default='Source URL', max_length=200),
        ),
    ]
