# Generated by Django 3.0.4 on 2020-04-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='object_id',
        ),
        migrations.AddField(
            model_name='hit',
            name='ip',
            field=models.CharField(default='ip', max_length=40),
        ),
        migrations.AddField(
            model_name='hit',
            name='session',
            field=models.CharField(default='session', max_length=40),
        ),
    ]
