# Generated by Django 3.0.4 on 2020-04-17 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'Answers must be greater than 1 character')]),
        ),
    ]
